apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtd-deployment
  labels:
    role: mtd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mtd-app
  template:
    metadata:
      labels:
        role: mtd-app
    spec:
      containers:
      - name: app-nginx
        image: "magalixcorp/flasksidecar"
      - name: web-nginx
        image: "magalixcorp/nginxsidecar"