apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-frontend
spec:
  selector:
    matchLabels:
      app: hello-frontend
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: server
          image: "kost13/apache-front-test"
