apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
spec:
  selector:
    matchLabels:
      app: hello-nginx
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-nginx
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "kost13/nginx-test"
