apiVersion: v1
kind: Service
metadata:
  name: wordpress-apache
  labels:
    app: wordpress-apache
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: wordpress-apache
    tier: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-apache
  labels:
    app: wordpress-apache
spec:
  selector:
    matchLabels:
      app: wordpress-apache
      tier: frontend
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress-apache
        tier: frontend
    spec:
      containers:
      - image: bitnami/wordpress:5.7.2
        name: wordpress-apache
        env:
        - name: WORDPRESS_DATABASE_NAME
          value: wordpress
        - name: WORDPRESS_DATABASE_USER
          value: wordpress
        - name: WORDPRESS_DATABASE_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 8080
          name: wordpress-apache
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
